apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: electric-shrimp-python 
  janus-idp.io/tekton: electric-shrimp-python
  backstage.io/kubernetes-id: electric-shrimp-python
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: electric-shrimp-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  